image: registry.gitlab.com/zerodogg/zd-gl-buildcontainer:latest

test:
    stage: test
    script:
        - make test

package:
    stage: build
    script:
        - make _gitlabdist
    only:
        - /^v\d/

stages:
    - test
    - build
